import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "./context/User";
import CookieChecker from "./middleware/checkUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <CookieChecker>
          <body className={inter.className}>{children}</body>
        </CookieChecker>
      </UserProvider>
    </html>
  );
}
